const ACCESS_TOKEN_STANDARD_LIFETIME = 15 * 60;
const REFRESH_TOKEN_STANDARD_LIFETIME = 30 * 24 * 60 * 60;
const REFRESH_TOKEN_SHORT_SESSION_LIFETIME = 24 * 60 * 60;

export const ACCESS_TOKEN = {
  NAME: "accessToken",
  COOKIE_MAX_AGE: ACCESS_TOKEN_STANDARD_LIFETIME * 1000,
  JWT_STANDARD_LIFETIME: ACCESS_TOKEN_STANDARD_LIFETIME,
};

export const REFRESH_TOKEN = {
  NAME: "refreshToken",
  COOKIE_MAX_AGE: REFRESH_TOKEN_STANDARD_LIFETIME * 1000,
  JWT_STANDARD_LIFETIME: REFRESH_TOKEN_STANDARD_LIFETIME,
  JWT_SHORT_SESSION_LIFETIME: REFRESH_TOKEN_SHORT_SESSION_LIFETIME,
};
