export const ACCESS_TOKEN_COOKIE_MAX_AGE = 15 * 60 * 1000;

export const REFRESH_TOKEN_COOKIE_MAX_AGE = 30 * 24 * 60 * 60 * 1000;

export const ACCESS_TOKEN_EXPIRES_IN = ACCESS_TOKEN_COOKIE_MAX_AGE / 1000;

export const REFRESH_TOKEN_EXPIRES_IN = REFRESH_TOKEN_COOKIE_MAX_AGE / 1000;

export const REFRESH_SESSION_TOKEN_EXPIRES_IN =
  (1 * 24 * 60 * 60 * 1000) / 1000;

export const ACCESS_TOKEN_NAME = "accessToken";

export const REFRESH_TOKEN_NAME = "refreshToken";

//TODO: I DON'R REALY LIKE THESE LONG HARD TO READ NAMES SHOULD I MAKE AN OBJECT OR SO ? IS TI POSIBLE IN ENV FILES?
// TO DEVIDE IT BY TOKEN OR COOKIE I SHOULD BE EASIER TO USE
// OH WAIT IT IS NOT ENV FILE  I SHOULD MAKE IT SIMPLER
