export const ACCESS_TOKEN_COOKIE_MAX_AGE = 15 * 60 * 1000;

export const REFRESH_TOKEN_COOKIE_MAX_AGE = 30 * 24 * 60 * 60 * 1000;

export const ACCESS_TOKEN_EXPIRES_IN = ACCESS_TOKEN_COOKIE_MAX_AGE / 1000;

export const REFRESH_TOKEN_EXPIRES_IN = REFRESH_TOKEN_COOKIE_MAX_AGE / 1000;

export const ACCESS_TOKEN_NAME = "accessToken";

export const REFRESH_TOKEN_NAME = "refreshToken";
